#!/bin/bash
# v0.2
# 12.11.2014
# 17.12.2014
# 

SCRIPT_HELP="
Apply patch.

Usage:
       {0} (path_file|path_url)"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drupal

echo "######################################"
echo "ALERT! THIS SCRIPT SHOULD BE REWRITED."
echo "IT USES PATCHES FROM DRUPAL ROOT, "
echo "SHOULD APPLY PATCH RELATIVE TO MODULE DIRECTORY."
echo "######################################"
echo ""

if [ -z "$1" ]; then
	usage
	exit 1
fi

src="$1"
patch_name="drupal.patch"
rej_name="patch.rej"
trap 'rm -f "$patch_name" "$rej_name"' EXIT

if [ -f "$src" ]; then
	#echo "copy patch from $src"
	cp "$src" "$patch_name"
else
	#echo "download patch $src"
	wget -q -O "$patch_name" "$src" > /dev/null
fi

if [ ! -f "$patch_name" ]; then
	echo >&2 "patch $patch_name not exists"
	exit 1
fi

patch --strip=1 --force --silent --reject-file="$rej_name" < "$patch_name"

if [ $? -ne 0 ]; then
	echo >&2 "patch error"
	exit 1
fi

log_text="$(date '+%Y-%m-%d %H:%M'); $PWD; $src"

if [ -f "$rej_name" ]; then
	# patch rejected
	echo "$log_text; patch failed"

	# I dont't know, how not to create backups, therefore clean backups for last 1 minute if reject
	# and .rej file
	find -cmin -1 -name "*.orig" -exec rm {} \;
	exit 1
else
	# patch success
	echo "$log_text; patch success"

	# change owner of patched files
	if [ $(whoami) = "root" ]; then
		user=$(stat -c '%U' $(pwd))
		find -mmin -1 -exec chown "$user":"$user" {} \;
	fi
fi
