#!/bin/bash
# v0.2
# 24.03.2014
# 24.12.2014 - added (--uri)
# 23.03.2015 - changed parameters

SCRIPT_HELP="
Run Drush cron in correct environment.

Usage:

       {0} root_path
        - run drush cron in root_path

       {0} root_path elysia-cron
        - run drush elysia-cron in root_path

       {0} root_path cron domain
        - run drush cron in root_path using domain.
          Need for override http://default, for simplenews.
          Default domain - basename of root_path"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

root_path="$1"

drush_command="cron" # elysia-cron
if [ $# -ge 2 ]; then
	drush_command="$2"
fi

if [ $# -ge 3 ]; then
	domain="$3"
else
	domain="${root_path##*/}"
fi
uri="http://$domain"

QUIET="--quiet"
if [ -n "$DRUPAL_SCRIPTS_TEST" ]; then
	QUIET=""
fi

cd "$root_path"
user=$(whoami)
env PATH=/usr/local/bin:/usr/bin:/bin USER="$user" COLUMNS=72 drush --root="$root_path" --uri="$uri" $QUIET $drush_command # 2>/dev/null
#echo env PATH=/usr/local/bin:/usr/bin:/bin USER="$user" COLUMNS=72 drush --root="$root_path" --uri="$uri" $drush_command >&2
