#!/bin/bash
# 23.02.2015
# v0.1

SCRIPT_HELP="
Cleans cache_ table and optimize it.
Delete only expired cache.

Usage:
       {0} cache_table_name

Options:
       -v Verbose mode"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drupal

if [ $# != 1 ]; then
	usage
	exit 1
fi

cache_table="$1"
if [ -z $(echo "$cache_table" | grep "^cache") ]; then
	echo >&2 "$cache_table not cache table!"
	exit 1
fi

count=$(drs sql "SELECT COUNT(*) FROM {${cache_table}} WHERE expire <> 0 AND expire < UNIX_TIMESTAMP()")

if [ "$count" -ne 0 ]; then
	drs sql "DELETE FROM {${cache_table}} WHERE expire <> 0 AND expire < UNIX_TIMESTAMP() LIMIT 5000"
	drs sql "OPTIMIZE TABLE {${cache_table}}" > /dev/null
fi

if [ -n "$SCRIPT_VERBOSE" ]; then
	echo >&2 "cleared $count rows from $cache_table"
fi
