#!/bin/bash
# 24.03.2015
# v0.1
# @var $DOCS_FILE from config

SCRIPT_HELP="
Show module brief module info from custom file with internal documentation.

Usage:

       {0}
        - output whole docs file

       {0} module_name
        - output lines about module

       {0} module_name docs_file
        - output lines about module from docs_file"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

if [ -n "$2" ]; then
	DOCS_FILE="$2"
fi

if [ ! -r "$DOCS_FILE" ]; then
	echo >&2 "DOCS_FILE $DOCS_FILE not found"
	exit 1
fi

module_name="$1"
if [ -z "$module_name" ]; then
	cat "$DOCS_FILE"
else
	help=$(grep "\(^\|\/\)$module_name\( -\|$\)" "$DOCS_FILE")
	if [ -n "$help" ]; then
		help2=$(grep -w "$module_name" "$DOCS_FILE" | grep -v "\(^\|\/\)$module_name\( -\|$\)")
	fi
	if [ -z "$help$help2" ]; then
		exit 1
	else
		if [ -n "$help" ]; then echo "$help"; fi
		if [ -n "$help2" ]; then echo "$help2"; fi
	fi
fi
