#!/usr/bin/env php
<?php
# v0.1
# 22.02.2015
# 07.03.2015 - arrays print and input pipes

function script_usage() {
  echo "drupal-decode v0.1

Decode serialized values from Drupal database.
Can decode variables and arrays.
true decodes as 1 and false as 0.
Arrays decodes as print_r.

Usage:

       drs decode \"serialized_string\"

       echo \"serialized_string\" | drs decode
";
}

if (isset($argv[1]) && $argv[1] == '--help') {
  script_usage();
  exit(1);
}

if (isset($argv[1])) {
  $serialized = $argv[1];
}
else {
  $serialized = trim(fgets(STDIN));
}

$val = @unserialize($serialized);
if ($val === FALSE && $serialized != 'b:0;') {
  fwrite(STDERR, "'$serialized' is not serialized string.\n");
  exit(1);
}

if (is_array($val)) {
  print_r($val);
}
else {
  if ($val === FALSE) {
    $val = 0;
  }
  if ($val === TRUE) {
    $val = 1;
  }
  echo $val . "\n";
}
