#!/bin/bash
# 22.02.2015 - faster than drush sqlq
# 23.03.2015 - replace {table} to table with prefix
# v0.2

SCRIPT_HELP="
Execute sql query.
Same as drush sql-query, but faster.

Usage: {0} \"query\"

Table names must be encapsulated in {} if db has prefixes, ex.
SELECT COUNT(*) FROM {node}

Output \"error\" if error occured.

Options:
    -v Verbose mode, output sql and connection parameters, explain sql errors"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drupal

if [ $# = 0 ]; then
	usage
	exit 1
fi

function s(){
	drs database-settings "$1"
}

function sql(){
	prefix=$(s prefix)
	sql=$(echo $1 | sed "s/{\(.*\?\)}/${prefix}\1/g")
	[ -n "$SCRIPT_VERBOSE" ] && echo >&2 "sql: $sql"

	connect_string="--user=\"$(s username)\" --password=\"$(s password)\" --host=\"$(s host)\" --port=\"$(s port)\" \"$(s database)\""

	[ -n "$SCRIPT_VERBOSE" ] && echo >&2 "connect: $connect_string"

	mysql -Brs --user="$(s username)" --password="$(s password)" --host="$(s host)" --port="$(s port)" "$(s database)" <<< "$sql"
}

function sqlq(){
	sql "$1" 2>/dev/null
}

if [ -n "$SCRIPT_VERBOSE" ]; then
	sql "$1"
else
	sqlq "$1"
	if [ $? -ne 0 ]; then
		echo "error"
		exit 1
	fi
fi
