#!/bin/bash
# 10.07.2014
# 22.02.2015
# 23.03.2015 - cache
# v0.2 - removed drush for speedup

SCRIPT_HELP="
List enabled modules.
Same as drush pml --status=enabled --type=module --pipe,
but faster and with cache.
Cache time defines in minutes, from MODULES_CACHE_TIME in config, default 10 minutes.

Options:
    -f Force check module, without cache"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drupal

if [[ ! "$MODULES_CACHE_TIME" =~ ^-?[0-9]+$ ]]; then
	MODULES_CACHE_TIME=10
fi

cache_file="/tmp/drupal-modules-enabled-$(echo $PWD | md5sum | cut -d' ' -f1)"
if [ -f "$cache_file" ] && [ ! -w "$cache_file" ]; then
	echo >&2 "cache file $cache_file not writable, aborting"
	exit 1
fi

if [ -z "$SCRIPT_FORCE" ] && [ -f "$cache_file" ] && [ $(find "$cache_file" -mmin -${MODULES_CACHE_TIME} | wc -l) = "1" ]; then
	cat "$cache_file"
	exit 0
fi

modules=$(drs sql "SELECT name FROM {system} WHERE type = 'module' AND status=1 AND filename NOT LIKE '%.profile' ORDER BY name")

> "$cache_file"
user=$(stat -c '%U' $PWD)
if [ "$(whoami)" != "$user" ]; then
	chown $user:$user "$cache_file"
	chmod 600 "$cache_file"
fi

for module in "$modules"; do
	echo "$module" >> "$cache_file"
done

cat "$cache_file"
