#!/bin/bash
# 08.01.2015
# v0.1

SCRIPT_HELP="
Install module, clean cache commit module to git.

Usage:
       {0} module_name [git_comment]"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drush
check_drupal

if [ $# = 0 ]; then
	usage
	exit 1
fi

module_name="$1"

comment="modules: $module_name"
if [ -n "$2" ]; then
	comment="$comment, $2"
fi

# TODO replace with drupal-module-enabled
if [ $(drush pml --status=enabled --pipe | grep -cx "$module_name") = 1 ]; then
	echo >&2 "module $module_name already enabled"
	exit 1
fi

drush en -y "$module_name" \
	&& drush cc all \
	&& git add "sites/all/modules/$module_name" \
	&& git commit -m "$comment"
