#!/bin/bash
# add drush cron every hour for user
# v0.2
# 03.03.2014
# 05.12.2014 - fixed duplicate cron add
# @var $DRUPAL_SCRIPTS_ROOT from config
# @var $SCRIPT_SIMULATE from drupal-scripts-init

SCRIPT_HELP="
Add drupal-cron-run to user system cron.

Cron job runs in random minute every 3 hours.
Cron job add to user-owner of root_path.

Options:
        -s Simulate mode, don't actually change the system"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drush
check_drupal

DRS_BINARY="$(which drs)"

if [ ! -r "$DRS_BINARY" ]; then
	echo >&2 "Script '$DRS_BINARY' not found, aborting."
	exit 1
fi

root_path="$PWD"
user=$(stat -c '%U' "$root_path")

temp_file=$(mktemp -t drupal-cron-add-XXXX)
trap 'rm -f "$temp_file"' EXIT

crontab -l -u "$user" > "$temp_file" 2>/dev/null

cron_command="$DRS_BINARY cron-run \"$root_path\""

if [ -n "$(grep "$cron_command" "$temp_file")" ]; then
	echo >&2 "drush was in cron, exit"
	exit 0
fi

mins=$(shuf -i 1-59 -n 1)
cron_line="$mins 0,6-21/3 * * * $cron_command"
echo "$cron_line" >> "$temp_file"

if [ -n "$SCRIPT_SIMULATE" ]; then
	cat "$temp_file"
else
	cat "$temp_file" | crontab -u "$user" -
fi
