#!/bin/bash
# 22.02.2015
# v0.2 - removed drush for speedup

SCRIPT_HELP="
Check module status.
Same as drush pml --status=enabled --type=module, but faster.
Outputs 1 or 0.

Options:
    -f Force check module, without cache"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drupal

module_name="$1"
#drupal-sql "SELECT COUNT(*) FROM system WHERE name='$module_name' AND type = 'module' AND status=1"
if [ -n "$SCRIPT_FORCE" ]; then
	drs modules-enabled -f | grep -xc "$module_name"
else
	drs modules-enabled | grep -xc "$module_name"
fi
