#!/usr/bin/env php
<?php
# 23.02.2015
# v0.1

$commands = array('database', 'username', 'password', 'prefix', 'host', 'port');

function script_usage($commands) {
  echo "drupal-database-settings v0.1

Shows database credentials from settings.php.

Usage:
       drs database-settings (" . implode('|', $commands) . ")
";
}

if (isset($argv[1]) && $argv[1] == '--help') {
  script_usage($commands);
  exit(1);
}

$settings_path = 'sites/default/settings.php';
if(!file_exists($settings_path)){
  fwrite(STDERR, "$settings_path not found\n");
  //echo "$settings_path not found\n";
  exit(1);
}
include($settings_path);

$settings_path = 'sites/default/settings.local.php';
if(file_exists($settings_path)){
  include($settings_path);
}

$command = $argv[1];
if (!in_array($command, $commands)) {
  script_usage($commands);
  exit(1);
}

echo $databases['default']['default'][$command] . "\n";
