#!/bin/bash
# 22.02.2015 - faster than drush sqlq
# 23.03.2015 - replace {table} to table with prefix
# v0.2

SCRIPT_HELP="
Execute sql query.
Same as drush sql-query, but faster.

Usage: {0} \"query\"

Table names must be encapsulated in {} if db has prefixes, ex.
SELECT COUNT(*) FROM {node}

Output \"error\" if error occured.

Options:
    -v Verbose mode, output sql and connection parameters, explain sql errors"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drupal

if [ $# = 0 ]; then
	usage
	exit 1
fi

function s(){
	drs database-settings "$1"
}

function sql(){
	prefix=$(s prefix)
	sql=$(echo $1 | sed "s/{\(.*\?\)}/${prefix}\1/g")
	[ -n "$SCRIPT_VERBOSE" ] && echo >&2 "sql: $sql"

	connect_string="-u$(s username) -p$(s password) -h$(s host)"
	if [ -n "$(s port)" ]; then
		connect_string="$connect_string -P$(s port)"
	fi
	connect_string="$connect_string $(s database)"

	[ -n "$SCRIPT_VERBOSE" ] && echo >&2 "connect: $connect_string"

	mysql -Brs $connect_string <<< "$sql"
}

function sqlq(){
	sql "$1" 2>/dev/null
}

if [ -n "$SCRIPT_VERBOSE" ]; then
	sql "$1"
else
	sqlq "$1"
	if [ $? -ne 0 ]; then
		echo "error"
		exit 1
	fi
fi
