#!/bin/bash
# 23.02.2015
# v0.2
# removed drush for speedup

SCRIPT_HELP="
Show count rows from table.
Same as drupal-sql \"SELECT COUNT(*) FROM {table_name}\".

Usage: {0} table_name

Output 0 if error occured."

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drupal

count=$(drs sql "SELECT COUNT(*) FROM {$1}")
if [ "$count" = "error" ]; then
	echo 0;
	exit 1
else
	echo "$count"
fi
