#!/bin/bash
# 23.02.2015
# v0.2
# removed drush for speedup

# old version 0.1
#val=$(drush vget "$1" --exact 2>&1 | grep "^$1: " | cut -d':' -f2 | tr -d ' ' | sed "s/'//g" | grep -v ERROR)
#if [ -z "$val" ]; then val=0; fi
#echo $val

SCRIPT_HELP="
Show Drupal variable.
Same as drush vget, but faster.

Usage: {0} var_name"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

if [ $# = 0 ]; then
	usage
	exit 1
fi

check_drupal

check_sql="SELECT COUNT(*) FROM {variable} WHERE name='$1'"
if [ -n "$SCRIPT_VERBOSE" ]; then
	result=$(drs sql -v "$check_sql")
else
	result=$(drs sql "$check_sql")
fi

if [ "$result" -eq 0 ]; then
	echo >&2 "variable '$1' not found"
	exit 1
fi

sql="SELECT value FROM {variable} WHERE name='$1'"
if [ -n "$SCRIPT_VERBOSE" ]; then
	result=$(drs sql -v "$sql")
else
	result=$(drs sql "$sql")
fi

if [ $? -ne 0 ]; then
	echo ""
	exit 1
fi

if [ -n "$result" ]; then
	result=$(drs decode "$result")
fi
if [ "$result" = "true" ]; then result=1; fi
if [ "$result" = "false" ]; then result=0; fi

echo "$result"
