#!/bin/bash
# 23.02.2015
# v0.1

SCRIPT_HELP="
Cleans cache_ table and optimize it.
Delete only expired cache.

Usage: {0} cache_table_name"

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init

check_drupal

if [ $# != 1 ]; then
	usage
	exit 1
fi

cache_table="$1"
if [ -z $(echo "$cache_table" | grep "^cache_") ]; then
	echo >&2 "$cache_table not cache table!"
	exit 1
fi

drs sql "DELETE FROM {${cache_table}} WHERE expire<UNIX_TIMESTAMP()" > /dev/null
drs sql "OPTIMIZE TABLE {${cache_table}}" > /dev/null
